export const HERODETPAGE: any[] = 
[{id: 2,
  language: 'English',
  heroDet_h1: 'details',
  heroDet_id: 'id',
  heroDet_category: 'category',
  heroDet_area: 'area',
  heroDet_subarea: 'subarea',
  heroDet_employee: 'employee',
  heroDet_email: 'email',
  heroDet_name: 'name',
  heroDet_assigneeid: 'assigneeid',
  heroDet_assignee: 'assignee',
  heroDet_reply: 'reply',
  heroDet_status: 'status',
  heroDet_back: 'back',
  heroDet_save: 'save'
},
{ id: 1,
  language: '中文',
  heroDet_h1: '详细',
  heroDet_id: 'id',
  heroDet_category: '类别',
  heroDet_area: '区域',
  heroDet_subarea: '子区域',
  heroDet_employee: '员工',
  heroDet_email: '邮箱',
  heroDet_name: '姓名',
  heroDet_assigneeid: '接单人id',
  heroDet_assignee: '接单人',
  heroDet_reply: '回复',
  heroDet_status: '状态',
  heroDet_back: '返回',
  heroDet_save: '保存'
}]