export const INCIDENTPAGE: any[] = 
[{id:2,
  language:'English',
  incident_h1: 'details',
  incident_id: 'id',
  incident_employee: 'employee',
  incident_email: 'email',
  incident_name: 'name',
  incident_assignee1: 'assignee',
  incident_assigneeid: 'assigneeid',
  incident_assignee2: 'assignee',
  incident_reply: 'reply',
  incident_status: 'status',
  incident_back: 'Back',
  incident_save: 'Save'
},
{ id:1,
  language:'中文',
  incident_h1: '详细',
  incident_id: 'id',
  incident_employee: '员工',
  incident_email: '邮箱',
  incident_name: '姓名',
  incident_assignee1: '接单人',
  incident_assigneeid: '接单人id',
  incident_assignee2: '接单人',
  incident_reply: '回复',
  incident_status: '状态',
  incident_back: '后退',
  incident_save: '保存'
}];